### PR TITLE
downstream changes

### PR DESCRIPTION
**Pull request by flawedworld**

### CODE REVIEW

**Comment by flawedworld** [comment]
Changes will now be within https://github.com/GrapheneOS/carriersettings-extractor

**Comment by daradib** [comment]
@flawedworld would you like me to transfer this repository to GrapheneOS? It was always intended for GrapheneOS and I think it would make more sense to be directly maintained there rather than as a separate fork.

**Comment by flawedworld** [comment]
Hey @daradib , just asked Daniel, that would be great. He would prefer if you transferred it to his GitHub https://github.com/thestinger first and then he will put it in the GrapheneOS organisation. Thanks!

**Comment by daradib** [comment]
Sure, done!

**Pull request closed without merging**
